### ISSUE TITLE
Birthday reminder feature

### ISSUE THREAD

**Issue by immolo** [csfore/gentodo#7]
Gentodo could be improved by reminding a week in advance of when an important birthday is coming up for someone you respect.

For example you could add a date of March 26th for my birthday and it would only show from the 19th of March then remove itself on the 27th until the following the year.

This could also be handy to finally remember to buy my mother a birthday card as well.

**Comment by immolo** [comment]
I would like to speak to Mr Jones about this!

**Comment by csfore** [comment]
Mr. Jones has been notified.
